-- MySQL Script generated by MySQL Workbench
-- Sun Feb 13 22:55:47 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Department`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Department` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Department` (
  `dept_id` INT NOT NULL,
  `dept_name` VARCHAR(45) NULL,
  `dept_address` VARCHAR(45) NULL,
  PRIMARY KEY (`dept_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Employee`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Employee` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Employee` (
  `employee_id` INT NOT NULL,
  `employee_name` VARCHAR(45) NOT NULL,
  `Department_dept_id` INT NOT NULL,
  PRIMARY KEY (`employee_id`, `Department_dept_id`),
  CONSTRAINT `fk_Employee_Department`
    FOREIGN KEY (`Department_dept_id`)
    REFERENCES `mydb`.`Department` (`dept_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Employee_Department_idx` ON `mydb`.`Employee` (`Department_dept_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Project`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Project` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Project` (
  `project_code` INT NOT NULL,
  `project_title` VARCHAR(45) NULL,
  `project_manager` VARCHAR(45) NULL,
  `project_budget` DECIMAL(10,2) NULL,
  `Employee_employee_id` INT NOT NULL,
  `Employee_Department_dept_id` INT NOT NULL,
  PRIMARY KEY (`project_code`, `Employee_employee_id`, `Employee_Department_dept_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Skill`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Skill` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Skill` (
  `skill_code` INT NOT NULL,
  `skill_type` VARCHAR(45) NULL,
  PRIMARY KEY (`skill_code`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Employee Project`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Employee Project` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Employee Project` (
  `Employee_employee_id` INT NOT NULL,
  `Project_project_code` INT NOT NULL,
  `Hourly_rate` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`Employee_employee_id`, `Project_project_code`),
  CONSTRAINT `fk_Employee_has_Project_Employee1`
    FOREIGN KEY (`Employee_employee_id`)
    REFERENCES `mydb`.`Employee` (`employee_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Employee_has_Project_Project1`
    FOREIGN KEY (`Project_project_code`)
    REFERENCES `mydb`.`Project` (`project_code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Employee_has_Project_Project1_idx` ON `mydb`.`Employee Project` (`Project_project_code` ASC) VISIBLE;

CREATE INDEX `fk_Employee_has_Project_Employee1_idx` ON `mydb`.`Employee Project` (`Employee_employee_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Employee Skill Level`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Employee Skill Level` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Employee Skill Level` (
  `Skill_skill_code` INT NOT NULL,
  `Employee_employee_id` INT NOT NULL,
  `Skill_level` INT NULL,
  PRIMARY KEY (`Skill_skill_code`, `Employee_employee_id`),
  CONSTRAINT `fk_Skill_has_Employee_Skill1`
    FOREIGN KEY (`Skill_skill_code`)
    REFERENCES `mydb`.`Skill` (`skill_code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Skill_has_Employee_Employee1`
    FOREIGN KEY (`Employee_employee_id`)
    REFERENCES `mydb`.`Employee` (`employee_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Skill_has_Employee_Employee1_idx` ON `mydb`.`Employee Skill Level` (`Employee_employee_id` ASC) VISIBLE;

CREATE INDEX `fk_Skill_has_Employee_Skill1_idx` ON `mydb`.`Employee Skill Level` (`Skill_skill_code` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
